### ISSUE TITLE
Investigate removing testify as a test dependency

### ISSUE THREAD

**Issue by joshdk** [joshdk/go-junit#32]
Look into removing `testify` from the tests. It's only really used for asserts, and is the *only* dependency in the repo.

Would removing this dependency be worth the loss of test usability?

**Comment by rafaribe** [comment]
Yes

**Comment by joshdk** [comment]
Hi @rafaribe !

Could you please tell me a little more about what you are experiencing? I originally opened this issue when (I believe) folks were running `make lint` and seeing the dependencies for `golangci-lint` scroll past.

If you are being negatively impacted by this test dep, I would like to learn more.

Cheers!
